### ISSUE TITLE
TODO List For v0.1.7

### ISSUE THREAD

**Issue by sjlleo** [OwO-Network/nexttrace-enhanced#1]
- [x] 快速测试加入配置文件中，可定制化
- [ ] 加入同步功能，可以通过Github Gist同步配置文件
- [x] 对配置进一步优化，加强互动性，以及定制化性
- [x] TCP SYN 不再并发，改为根据TTL逐步进行
- [x] Web API 初步支持
